### ISSUE TITLE
Make icon better

### ISSUE THREAD

**Issue by hroncok** [syky27/LunchGuy#1]
@mmajko

Please, create a better icon, here is the svg.

[obedar_icon.zip](https://github.com/syky27/lunch_guy-ios/files/294443/obedar_icon.zip)

**Comment by marianhlavac** [comment]
Will do.

**Comment by syky27** [comment]
@mmajko Feel free tom come up with whole new design if you can.

**Comment by hroncok** [comment]
I'm not familiar with iOS development at all, but if this was my project I would create a build script, that would create the necessary bitmaps from the svg, keeping only the svg in git.

**Comment by marianhlavac** [comment]
@syky27 Why new design? I like this one :)

**Comment by syky27** [comment]
@mmajko I would be awesome to come up with something unique, for example autogeneration of images according to names of the meals... :D

**Comment by syky27** [comment]
@hroncok see: 065372611f1035dcf0c96ac500929bce323822da

**Comment by syky27** [comment]
@mmajko please replace icon/icon.svg in your PR, and please note the commit convention, I know that there is no contribution guide (yet), but please respect used convention.

**Comment by marianhlavac** [comment]
I made a few color variations, maybe you'll prefer one of the variations with gradient. :) But we can always stick with the original one, only slightly zoomed out and with lighter foreground color. ;)

### Option 1 - Original

flat, white foreground, blue background
- [UI preview](https://cloud.githubusercontent.com/assets/3010503/15795209/ce593f2e-29ef-11e6-9512-002f83c66f66.png)

![lev_obedar_original](https://cloud.githubusercontent.com/assets/3010503/15795206/ca6fe764-29ef-11e6-9377-997f2cc91188.png)

### Option 2 - Gradient Light

gradient, blue foreground, light background
- [UI preview](https://cloud.githubusercontent.com/assets/3010503/15795230/1111474e-29f0-11e6-9fc2-d0285b79b1ab.png)

![lev_obedar_bluewhite](https://cloud.githubusercontent.com/assets/3010503/15795228/0e93dbb2-29f0-11e6-9a40-c30d239ce864.png)

### Option 3 - Gradient Dark

gradient, white foreground, blue background
- [UI preview](https://cloud.githubusercontent.com/assets/3010503/15795236/16acba12-29f0-11e6-8a09-a261c871dac0.png)

![lev_obedar_whiteblue](https://cloud.githubusercontent.com/assets/3010503/15795233/13abf8e6-29f0-11e6-9d10-a1b5c1e35a03.png)

---

The question is - **which one?** Or maybe even completely different color scheme?

**Comment by hroncok** [comment]
I like option 3 the most.

**Comment by syky27** [comment]
Me too.

**Comment by syky27** [comment]
@mmajko Would you be able to give me the Icon in 1024x1024? Please?

**Comment by marianhlavac** [comment]
If there are source files somewhere...

**Comment by marianhlavac** [comment]
If not, I'd have to search my HDD, but not sure if I kept them.

**Comment by syky27** [comment]
@mmajko All I have is this, to upload new version 1024x1024 is needed.

https://github.com/syky27/lunch_guy-ios/tree/dev/LunchGuy/Assets.xcassets/AppIcon.appiconset

**Comment by syky27** [comment]
@mmajko dont worry about it, it is actually here https://github.com/syky27/lunch_guy-ios/tree/dev/icon
