### ISSUE TITLE
Get rid of following dependencies

### ISSUE THREAD

**Issue by syky27** [syky27/LunchGuy#11]
`pod 'SwiftyJSON'` replace with swift4 native JSON Codable parsing

`pod 'RealmSwift'` no need to persist anything, Realm was just for testing...

`pod 'SwiftFetchedResultsController'` This is so useless...

**Comment by josefdolezal** [comment]
Hey @syky27, are you working on this? I can fix this together with #8 and #12 if you are ok with it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by syky27** [comment]
@josefdolezal Thanks, API URL changed so it  fixes #8 (https://github.com/tomaskadlec/lunch_guy/issues/65)

I will be more than happy if you could fix this, I got tons of other work.

Thanks

**Comment by josefdolezal** [comment]
This one may be closed, fixed in #15.
