### ISSUE TITLE
App localization

### ISSUE THREAD

**Issue by josefdolezal** [syky27/LunchGuy#22]
Hey @syky27, I would like to propose changes in app localization.

## Context
Currently the app is only localized to Czech. However, some strings are displayed in English. We should implement separate localization for both languages and use the one that user has set as default in system preferences. We should also remove the string literals from controllers source code.

## Proposal
Create separate `localizable.strings` files for Czech and English. Then, wen use SwiftGen to generate localization enums so we can get rid off string literals 🎉.

As always, this issue is open for discussion and I can take care of implementation.

**Comment by syky27** [comment]
I agree, I might be for consideration to try to translate meal name via some third party service, if exists...

**Comment by josefdolezal** [comment]
I was thinking about it, but it would not make sense. We would have to translate each meal separately which would result in huge number of requests. Also, the names would awkward I guess.

**Comment by syky27** [comment]
@josefdolezal Shall this be closed due #24 ?

**Comment by josefdolezal** [comment]
Definitely, I will close it.
