### ISSUE TITLE
Screen empty states

### ISSUE THREAD

**Issue by josefdolezal** [syky27/LunchGuy#23]
Hey @syky, I would like to open discussion about empty screens design.

## Context
Time to time, menus for some restaurants are not available and the screen is empty without any information.

## Proposal
For restaurant list and menu detail, we may implement 'empty state'. This would just simple view with illustration and text like "No restaurant available." and "No menu for today.". This does not implement any new feature but makes better UX.

Unfortunately, my taste in graphic is wild and I am not sure if I can design it nicely. I can give it a try, but it would be super cool if someone other made at least draft. If not, I can create some simple designs before implementing it.

**Comment by syky27** [comment]
I agree, and I think that @mmajko might be willing to make that graphic....

**Comment by syky27** [comment]
#26
