### ISSUE TITLE
Guideline 4.2.2 - Design - Minimum Functionality

### ISSUE THREAD

**Issue by akhil7188** [syky27/LunchGuy#25]
I am trying to upload my app to app store. But it got rejected for two time now with "Guideline 4.2.2". I am attaching the screen shots below please suggest what i can do to make this approved.

![img_0540](https://user-images.githubusercontent.com/42545174/44345867-1946bb80-a4b2-11e8-82ee-2744dade802c.PNG)
![img_0541](https://user-images.githubusercontent.com/42545174/44345868-1946bb80-a4b2-11e8-9f01-93ecae854ec8.PNG)
![img_0547](https://user-images.githubusercontent.com/42545174/44345895-324f6c80-a4b2-11e8-9e9f-a3ef7a9adc8b.PNG)
![img_0548](https://user-images.githubusercontent.com/42545174/44345896-32e80300-a4b2-11e8-8415-b250835ab85f.PNG)
![img_0549](https://user-images.githubusercontent.com/42545174/44345899-34193000-a4b2-11e8-8cdc-98089a207112.PNG)
![img_0550](https://user-images.githubusercontent.com/42545174/44345908-3bd8d480-a4b2-11e8-8ca3-0d3803c2ba0e.PNG)

if you want i can add you to testflight.

**Comment by syky27** [comment]
Add functionality...

**Comment by akhil7188** [comment]
but what functionality i can add. As i added all the features i required.

**Comment by syky27** [comment]
You require not enought...
