### ISSUE TITLE
Missing restaurants on the list

### ISSUE THREAD

**Issue by Draken257** [syky27/LunchGuy#8]
i opened the app and restaurants missing on the list.
>iOS 11.

![img-2414](https://user-images.githubusercontent.com/32217639/30772656-1926a0a4-a060-11e7-8bed-be61a494e349.PNG)

**Comment by syky27** [comment]
Waiting deployment to AppStore.

**Comment by josefdolezal** [comment]
Hey @Draken257, this is now resolved in dev branch. I think this issue can be closed since new version may be deployed soon, right @syky27?

**Comment by josefdolezal** [comment]
Huh, didn't see your comment, sorry!

**Comment by syky27** [comment]
I would close is as soon as it gets into App Store.

**Comment by josefdolezal** [comment]
The update is live, I think that we can close this one.
